apiVersion: v1
kind: Service
metadata:
  name: automailhelpdesk-app-service
  labels:
    app: automailhelpdesk
    component: app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: automailhelpdesk
    component: app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: automailhelpdesk-ingress
  labels:
    app: automailhelpdesk
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - automailhelpdesk.yourdomain.com
    secretName: automailhelpdesk-tls
  rules:
  - host: automailhelpdesk.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: automailhelpdesk-app-service
            port:
              number: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: automailhelpdesk-config
  labels:
    app: automailhelpdesk
data:
  default.yaml: |
    # Application settings
    app:
      name: "AutoMailHelpdesk"
      version: "1.0.0"
      debug: false
      host: "0.0.0.0"
      port: 8000
      workers: 4

    # Processing configuration
    processing:
      max_retries: 3
      retry_delay: 60
      circuit_breaker:
        failure_threshold: 5
        recovery_timeout: 60
      batch_size: 10
      timeout: 300

    # Email processing configuration
    email:
      deduplication_window: 3600
      max_attachment_size: 10485760
      allowed_attachment_types:
        - "pdf"
        - "doc"
        - "docx"
        - "txt"
        - "jpg"
        - "jpeg"
        - "png"

    # Intent classification configuration
    intent:
      confidence_threshold: 0.7
      fallback_intent: "fallback_human"

    # RAG configuration
    rag:
      max_context_length: 2000
      similarity_threshold: 0.8
      max_results: 5
      chunk_size: 1000
      chunk_overlap: 200

  logging.yaml: |
    version: 1
    disable_existing_loggers: false

    formatters:
      json:
        format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d}'
        datefmt: '%Y-%m-%dT%H:%M:%S'

    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: json
        stream: ext://sys.stdout

    loggers:
      src:
        level: INFO
        handlers: [console]
        propagate: false

    root:
      level: INFO
      handlers: [console]

