version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d}'
    datefmt: '%Y-%m-%dT%H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/automailhelpdesk.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  # Application loggers
  src:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  src.workers:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  src.modules:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  # Third-party loggers
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false
  
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: false
  
  fastapi:
    level: INFO
    handlers: [console]
    propagate: false
  
  sqlalchemy:
    level: WARNING
    handlers: [console]
    propagate: false
  
  sqlalchemy.engine:
    level: WARNING
    handlers: [console]
    propagate: false
  
  celery:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  celery.worker:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  celery.task:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  googleapiclient:
    level: WARNING
    handlers: [console]
    propagate: false
  
  google:
    level: WARNING
    handlers: [console]
    propagate: false
  
  langchain:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  chromadb:
    level: WARNING
    handlers: [console]
    propagate: false
  
  httpx:
    level: WARNING
    handlers: [console]
    propagate: false
  
  aiohttp:
    level: WARNING
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console, error_file]

